### ISSUE TITLE
Cats support ?

### ISSUE THREAD

**Issue by ronanM** [lancewalton/treelog#10]
Any plan to support http://typelevel.org/cats ?

**Comment by channingwalton** [comment]
Hi,
there is a vague plan to do it. We currently publish three versions of the library already, adding a 4th is probably no big deal.

I'll see what I can do.

**Comment by channingwalton** [comment]
closing this - I just need to publish it as a proper version (in the next day or so)

**Comment by channingwalton** [comment]
released
