### ISSUE TITLE
Can we handle `IO` values in treelog??

### ISSUE THREAD

**Issue by everpeace** [lancewalton/treelog#13]
Hi!  I'm thinking how treelog can handle monadic values (e.g. `IO[V]`) in treelog.

In our use case, we want to handle `IO[V]` values with treelog like below.

```
  # This is just an ideal example
  # This doesn't compile
  import scalaz._
  import Scalaz._
  import effect.{IO, _}
  import IO._
  val comp = for {
    line1 <- readLn ~> ("line1 read: " + _)  // this is expected to produce a description of "line1 read:  <line input>"
    res <- putStrLn(line1: String) ~> ("put str:" + _) // this is expected to produce a description of "put str: <line1>"
  } yield {
    res
  } // This is expected to produce a value of type DescribedComputation[IO[String]] or similar
```

It seems `DescribeComputation` support `F` values such that it is `Monad` and `Traverse` in `BranchLabelingSyntax`.  However, `IO` is just `Monad` but not `Traverse` unfortunately...  

Can we handle `IO` values with treelog?  If not, how could we modify treelog to support `IO` values?? 

Thanks,

**Comment by channingwalton** [comment]
Hi,

I am going to have to think about this a little to understand what it means :D

I’ll do some experiments.

regards,

Channing

Channing Walton
+44 (0) 7980 294809
@channingwalton

**Comment by lancewalton** [comment]
I don't think this is possible because I don't think it's possible to implement Traverse[IO] without running the IO.

This is unfortunate because just the other day I needed Traverse[IO] for something else & had to bail in the end. I might be wrong, but I could not see how to do it.

**Comment by everpeace** [comment]
Thank you for your response!  

Actually, I was trying to tackle this problem. As a result, I could make monad transformer `DescribedComputationT` for `DescribedComputation`.

see my gist for full source code:
https://gist.github.com/everpeace/daac16f854cf9e75f5f4ed433c384fd2

The transformer enables us this:
```
  val comp = for {
    _    <- putStr("input some string> ") ~> ("putStr(input some string): " + _)  // this returns DescribedComputationT[IO, Unit]
    line <- readLn ~> ("readLn: " + _)                                            // this returns DescribedComputationT[IO, String]
    res <- putStrLn(line) ~> ("putStrLn(line): " + _)                             // this returns DescribedComputationT[IO, Unit]
  } yield {
    res
  }

  println("# Performing unsafePerformIO")
  val writer =  comp.run.unsafePerformIO.run

  println()
  println("# Output described computation results")
  println(writer.written.shows)
  println(writer.value)

// This program outputs below:
// # Performing unsafePerformIO
// input some string> abcd
// abcd
//
// # Output described computation results
// No Description
//   putStr(input some string): ()
//   readLn: abcd
//   putStrLn(line): ()
// \/-(())
```

However, I am not sure this transformer satisfies several laws (e.g. monad law, monad transformer law)...
I will write property-based tests for checking the transformer satisfies some required laws as a next step.

**Comment by everpeace** [comment]
I added property based tests in my forked repo's `DescribedComputationT` branch.

https://github.com/everpeace/treelog/blob/DescribedComputationT/src/test/scala/DescribedComputationTransformer.scala#L102-L135

I confirmed my `DescribedComputationT` satisfies functor, monad, monadtrans laws for `DescribedComputationT[Option,?]`, `DescribedComputationT[Maybe,?],`DescribedComputationT[List,?]` and `DescribedComputationT[Tree,?]` types.

**Comment by channingwalton** [comment]
Thank you very much for doing this! Can you make a pull request for this and we'll get it merged in?

**Comment by everpeace** [comment]
Sure!  I need to move some codes and cosmetics.  I will make a PR in a few days 👍

**Comment by everpeace** [comment]
@channingwalton I opened #14 just now.  

I'm looking forward to having some feedbacks.
