### ISSUE TITLE
Implement DescribedComputationT for cats

### ISSUE THREAD

**Issue by ghost** [lancewalton/treelog#15]
Hi,
Please implement DescribedComputationT for cats version. Thank you. Here is my rogue implementation copied from scalaz version:

case class DescribedComputationT[F[_] : Monad, A](run: F[DescribedComputation[A]]) {

  def map[B](f: A => B): DescribedComputationT[F, B] = {
    DescribedComputationT(implicitly[Monad[F]].map(run)(_ map f))
  }

  def flatMap[B](f: A => DescribedComputationT[F, B]): DescribedComputationT[F, B] = {
    val v: F[DescribedComputation[B]] = implicitly[Monad[F]].flatMap(run) { dcA =>
      dcA.value.run._2 match {
        case Right(a) =>
          // if dcA succeeded,
          for {
            dcB <- f(a).run // compute another described computation returning B
          } yield {
            // we can concatenate computation history like this.
            for {
              _ <- dcA // we can drop returned value because we just need to concatenate descriptions.
              b <- dcB // extracting final result of type B
            } yield b // final result of this described computation should be B
          }
        case Left(_) =>
          // if previous computation failed, we just return the history.
          // but we need to convert type of return value into B.
          run.map(_.map(_.asInstanceOf[B]))
      }
    }
    // need to wrap DescribedComputation finally
    DescribedComputationT(v)
  }
}

**Comment by channingwalton** [comment]
Thanks for this. I'll have a look today.

**Comment by channingwalton** [comment]
Sorry I didn't get a chance to do this. Would you be able to submit a pull request against the cats branch?

**Comment by channingwalton** [comment]
'Twas done some time ago.
