### ISSUE TITLE
Metrics for how this effects performance vs other logging solutions.

### ISSUE THREAD

**Issue by Jacoby6000** [lancewalton/treelog#17]

**Comment by channingwalton** [comment]
Treelog doesn't actually do logging in the sense that log4j and other logging frameworks. The 'log' is retained in memory. You are then free to log more conventionally with the result.

**Comment by Jacoby6000** [comment]
Ah I see. It would still be nice to somehow gauge how this affects performance, but I suppose that's more an exercise for users.

**Comment by channingwalton** [comment]
Each 'logging' statement results in a method call, map or flatMap in effect, and a new monad instance so its pretty small I would say.
