### ISSUE TITLE
Unicode symbols in scaladoc not rendering correctly

### ISSUE THREAD

**Issue by refried** [lancewalton/treelog#8]
Haven’t investigated, but what I assume are Unicode characters in the scaladoc linked from the readme aren’t rendering correctly on iOS
Eg: `￢ﾆﾐ` shows where I expect a left single arrow,  `￢ﾇﾒ`shows where I expect a right double-arrow.  Maybe want to switch them to `<-` and `=>` respectively?

**Comment by channingwalton** [comment]
just saw this - sorry.

I believe I've fixed this and it will appear soon.
